"""Init databases.

Revision ID: b93bf6722249
Revises:
Create Date: 2023-09-28 10:08:13.462442

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b93bf6722249"
down_revision: str | None = None
branch_labels: str | (Sequence[str] | None) = None
depends_on: str | (Sequence[str] | None) = None


def upgrade() -> None:
    """Commands auto generated by Alembic - please adjust."""
    op.create_table("link",
    sa.Column("visit_time", sa.Integer(), nullable=False),
    sa.Column("link", sa.String(), nullable=False),
    sa.Column("domain", sa.String(), nullable=False),
    sa.Column("pk", sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint("pk", name=op.f("link_pk_pkey")),
    )


def downgrade() -> None:
    """Commands auto generated by Alembic - please adjust."""
    op.drop_table("link")
