# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.6.1
        poetry install
    - name: Lint with ruff
      run: |
        poetry run ruff .
    - name: Type check with mypy
      run: |
        poetry run mypy .
    - name: Dependencies check with deptry
      run: |
        poetry run deptry .
    - name: Test with pytest
      run: |
        pytest
